--- #YAML:1.0
name: Mozilla-Backup
version: 0.04
author:
  - Robert Rothenberg <rrwo at cpan.org>
abstract: Backup utility for Mozilla profiles
license: perl
requires:
  Archive::Zip: 0
  Carp: 0
  Config::IniFiles: 0
  File::Copy: 0
  File::Find: 0
  File::Spec: 0
  File::Temp: 0
  Log::Dispatch: 1.6
  Module::Pluggable: 0
  Params::Smart: 0.03
  Params::Validate: 0
  perl: 5.6.0
recommends:
  Getopt::Long: 0
  Log::Dispatch::Screen: 0
  Test::Pod: 1
  Test::Pod::Coverage: 0
build_requires:
  Test::More: 0
provides:
  Mozilla::Backup:
    file: lib/Mozilla/Backup.pm
    version: 0.04
  Mozilla::Backup::Plugin::FileCopy:
    file: lib/Mozilla/Backup/Plugin/FileCopy.pm
    version: 0.01
  Mozilla::Backup::Plugin::Zip:
    file: lib/Mozilla/Backup/Plugin/Zip.pm
    version: 0.01
generated_by: Module::Build version 0.2607
