--- #YAML:1.0
name: Mozilla-Backup
version: 0.06
author:
  - Robert Rothenberg <rrwo at cpan.org>
abstract: Backup utility for Mozilla profiles
license: perl
requires:
  Archive::Tar: 0
  Archive::Zip: 0
  Carp: 0
  Compress::Zlib: 0
  Config::IniFiles: 0
  File::Copy: 0
  File::Find: 0
  File::Spec: 0
  File::Temp: 0
  IO::File: 0
  IO::Zlib: 0
  Log::Dispatch: 1.6
  Module::Pluggable: 0
  Params::Smart: 0.05
  Regexp::Assemble: 0
  Regexp::Common: 1.8
  Return::Value: 0
  perl: 5.6.0
recommends:
  Getopt::Long: 0
  Log::Dispatch::Screen: 0
  Pod::Readme: 0.02
  Test::Pod: 1
  Test::Pod::Coverage: 0
  Test::Portability::Files: 0
build_requires:
  Test::More: 0
provides:
  Mozilla::Backup:
    file: lib/Mozilla/Backup.pm
    version: 0.06
  Mozilla::Backup::Plugin::FileCopy:
    file: lib/Mozilla/Backup/Plugin/FileCopy.pm
    version: 0.03
  Mozilla::Backup::Plugin::Tar:
    file: lib/Mozilla/Backup/Plugin/Tar.pm
    version: 0.02
  Mozilla::Backup::Plugin::Zip:
    file: lib/Mozilla/Backup/Plugin/Zip.pm
    version: 0.03
  Mozilla::ProfilesIni:
    file: lib/Mozilla/ProfilesIni.pm
    version: 0.02
generated_by: Module::Build version 0.261
