--- #YAML:1.0
name: Mozilla-Backup
version: 0.02
author:
  - Robert Rothenberg <rrwo at cpan.org>
abstract: Backup utility for Mozilla profiles
license: perl
requires:
  Archive::Zip: 0
  Carp: 0
  Config::IniFiles: 0
  File::Find: 0
  File::Spec: 0
  Log::Dispatch: 1.6
  Params::Validate: 0
  perl: 5.6.0
build_requires:
  File::Temp: 0
  Test::More: 0
provides:
  Mozilla::Backup:
    file: lib/Mozilla/Backup.pm
    version: 0.02
generated_by: Module::Build version 0.2607
